version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres


  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: furniture-store

    volumes:
      - postgres_data:/var/lib/postgresql/data  # Mount the volume to persist PostgreSQL data

volumes:
  postgres_data:  # Define a named volume to persist data