version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: furniture-store
    volumes:
      - mongo_data:/data/db  # Mount the volume to persist MongoDB data

volumes:
  mongo_data:  # Define a named volume to persist data
